# Try Catch 

try:
    num = 15/5
    print(num)
except:
    print('Something Went Wrong ')
finally:
    print('This is Done ')

